name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Cache dependencies
        id: cache-npm
        uses: threeal/cache-action@v0.1.0
        with:
          key: app-npm
          version: ${{ hashFiles('app/package-lock.json') }}
          files: app/node_modules

      - name: Install dependencies
        if: steps.cache-npm.outputs.restored == 'false'
        working-directory: app
        run: npm install

      - name: Check formatting
        working-directory: app
        run: npm run format-check

      - name: Run static analysis
        working-directory: app
        run: npm run lint

      - name: Test app
        working-directory: app
        run: npm test

      - name: Build app
        working-directory: app
        run: npm run build

      - name: Deploy app
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          folder: app/build
